---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: xds-server-user
 namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: xds-server-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xds-server-rbac
subjects:
  - kind: ServiceAccount
    name: xds-server-user
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: xds-server-reader
  apiGroup: rbac.authorization.k8s.io